namespace InferenceService.Models.Dto;

/// <summary>
/// Represents a Data Transfer Object (DTO) for the result of an inference process.
/// </summary>
public sealed record InferenceResultDto
{
    /// <summary>
    /// ID
    /// </summary>
    public Guid Id { get; init; }

    /// <summary>
    /// Gets the list of playlists generated by the inference process.
    /// </summary>
    public List<InferenceMetadataDto> Metadata { get; init; } = [];

    /// <summary>
    /// Gets the information about the model used for inference.
    /// </summary>
    public string ModelInfo { get; init; } = string.Empty;
}
