using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Repository.Abstractions.Extensions;
using Repository.Abstractions.Interfaces.BaseEntity;

namespace InferenceService.Models.Entities;

/// <summary>
/// Represents the result of an inference process.
/// </summary>
public sealed class InferenceResult : IBaseEntity<Guid>
{
    /// <summary>
    /// .ctor
    /// </summary>
    public InferenceResult()
    {
        Id = Guid.NewGuid();
    }
    
    /// <summary>
    /// Gets or sets the unique identifier for the inference result.
    /// </summary>
    public Guid Id { get; private set; }

    /// <summary>
    /// Gets or sets the unique identifier for the track associated with the inference result.
    /// </summary>
    [PartitionKey]
    public Guid TrackId { get; init; }

    /// <summary>
    /// User ID
    /// </summary>
    //[PartitionKey]
    public Guid SpredUserId { get; init; }

    /// <summary>
    /// Gets or sets the list of metadata generated by the inference process.
    /// </summary>
    [JsonInclude]
    public IList<InferenceMetadata> Metadata { get; set; } = [];

    /// <summary>
    /// Gets or sets the version of the model used for inference.
    /// </summary>
    [StringLength(100)]
    public string ModelVersion { get; init; } = string.Empty;

    /// <summary>
    /// Gets the date and time when the inference result was created.
    /// </summary>
    public DateTime CreatedAt { get; } = DateTime.Now;
    
    /// <summary>
    /// Update time
    /// </summary>
    public DateTime UpdatedAt { get; set; } = DateTime.Now;
    
    /// <summary>
    /// Last Unlock
    /// </summary>
    public DateTime? LastUnlock { get; set; } = null;
    
    /// <summary>
    /// TimeStamp
    /// </summary>
    public long Timestamp { get; private set; }

    /// <summary>
    /// Concurrency tag
    /// </summary>
    public string? ETag { get; private set; }
}

/// <summary>
/// Represents a playlist generated by the inference process.
/// </summary>
public sealed class InferenceMetadata
{
    /// <summary>
    /// Gets or sets the unique identifier for the playlist.
    /// </summary>
    public Guid MetadataId { get; init; }
    
    /// <summary>
    /// Playlist owner id
    /// </summary>
    public Guid MetadataOwner { get; init; }
    
    /// <summary>
    /// Catalog type
    /// </summary>
    public string Type { get; init; }

    /// <summary>
    /// Gets or sets the score assigned to the playlist by the inference process.
    /// </summary>
    public float Score { get; init; }

    /// <summary>
    /// Gets or sets the Reaction assigned to the playlist by the inference process.
    /// </summary>
    [JsonInclude]
    public required ReactionStatus Reaction { get; set; }

    /// <summary>
    /// Similar tracks
    /// </summary>
    [JsonInclude]
    public IList<SimilarTrack> SimilarTracks { get; set; } = [];

    /// <summary>
    /// Gets or sets a value indicating whether the metadata is locked for the user.
    /// </summary>
    public bool IsLocked { get; set; } = true;

    /// <summary>
    /// Indicates whether the metadata was unlocked as part of a premium user's benefits.
    /// </summary>
    public bool WasUnlockedByPremium { get; set; }

    /// <summary>
    /// Gets or sets the date and time when the content will be unlocked, or null if no unlock date is set.
    /// </summary>
    public DateTime? UnlockDate { get; set; }
}

/// <summary>
/// User Reaction
/// </summary>
public sealed class ReactionStatus
{
    /// <summary>
    /// Default .ctor
    /// </summary>
    public ReactionStatus()
    {
        IsLiked = null;
        HasApplied = null;
        WasAccepted = null;
    }
    
    /// <summary>
    /// Is Liked
    /// </summary>
    public bool? IsLiked { get; set; }
    
    /// <summary>
    /// Is applied
    /// </summary>
    public bool? HasApplied { get; set; }
    
    /// <summary>
    /// Is accepted
    /// </summary>
    public bool? WasAccepted { get; set; }
}

/// <summary>
/// Similar track
/// </summary>
public sealed class SimilarTrack
{
    /// <summary>
    /// Track ID
    /// </summary>
    public Guid SimilarTrackId { get; init; }
    
    /// <summary>
    /// Spred user ID.
    /// </summary>
    public Guid TrackOwner { get; init; }
    
    /// <summary>
    /// Similarity
    /// </summary>
    public float Similarity { get; init; }
}
