export const PATH = {
    INDEX: "/",
    LOGIN: "/login",
    LOGOUT: "/logout",
    PRIVACY_POLICY: "/privacy-policy",
    TERMS_OF_USE: "/terms-of-use",
    CALLBACK: "/callback",
    ERROR: "/error",
    NOT_FOUND: "/not-found",
    LOADING: "/loading",

    ARTIST: {
        ROOT: "/artist",
        PROFILE: "/artist/profile",
        TRACKS: "/artist/tracks",
        TRACK: "/artist/tracks/:trackId",
        UPLOAD: "/artist/upload",
        PLAYLISTS: "/artist/playlists",
        FEEDBACK: "/artist/feedback",
        MATCHES: "/artist/matches",
        HISTORY: "/artist/history",
        SETTINGS: "/artist/settings",
    },

    CURATOR: {
        ROOT: "/curator",
        PROFILE: "/curator/profile",
        TRACKS: "/curator/tracks",
        TRACK: "/curator/tracks/:trackId",
        SUBMISSIONS: "/curator/submissions",
        PLAYLISTS: "/curator/playlists",
        FEEDBACK: "/curator/feedback",
        MATCHES: "/curator/matches",
        HISTORY: "/curator/history",
        SETTINGS: "/curator/settings",
    },

    LABEL: {
        ROOT: "/label",
        PROFILE: "/label/profile",
        ARTISTS: "/label/artists",
        TRACKS: "/label/tracks",
        TRACK: "/label/tracks/:trackId",
        PLAYLISTS: "/label/playlists",
        FEEDBACK: "/label/feedback",
        MATCHES: "/label/matches",
        HISTORY: "/label/history",
        SETTINGS: "/label/settings",
    },
};